// web/src/pages/Procedures.tsx
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
	Button,
	HTMLTable,
	HTMLSelect,
	InputGroup,
	Tag,
	Dialog,
	DialogBody,
	DialogFooter,
	FormGroup
} from '@blueprintjs/core';
import { toast } from '../lib/toaster';
import { statusIntent } from '../lib/ui';
import Combobox from '../components/Combobox';
import {
	type Proc,
	usePrereqLib,
	usePrereqTypes,
	useProcedures,
	useCreateProcedure,
	useCreatePrereqType,
	useCreatePrereq
} from '../lib/queries';

const STATE_ITEMS = [
	{ value: 'ALL', label: 'All statuses' },
	{ value: 'DRAFT', label: 'Draft' },
	{ value: 'IN_REVIEW', label: 'In review' },
	{ value: 'APPROVED', label: 'Approved' },
	{ value: 'EFFECTIVE', label: 'Effective' },
	{ value: 'UNDER_REVIEW', label: 'Under review' },
	{ value: 'RETIRED', label: 'Retired' }
];

const TYPE_ITEMS = [
	{ value: 'SOP', label: 'SOP' },
	{ value: 'POLICY', label: 'Policy' },
	{ value: 'WORK_INSTRUCTION', label: 'Work instruction' },
	{ value: 'FORM', label: 'Form' },
	{ value: 'JOB_AID', label: 'Job aid' }
];

type SortKey = keyof Proc;
type PrereqLine = { type: string; text: string };

const prereqLabel = (p: { type: string; text: string }) => (p.type ? `${p.type}: ${p.text}` : p.text);

export default function Procedures() {
	const navigate = useNavigate();
	const [state, setState] = useState('ALL');
	const { data: procData, isLoading: loading } = useProcedures(state);
	const rows = useMemo(() => procData ?? [], [procData]);
	const [q, setQ] = useState('');
	const [sortKey, setSortKey] = useState<SortKey>('documentNumber');
	const [sortDir, setSortDir] = useState<1 | -1>(1);

	// create dialog
	const [showNew, setShowNew] = useState(false);
	const [docType, setDocType] = useState('SOP');
	const [title, setTitle] = useState('');

	// prerequisites for the create dialog: pick a type, then pick-or-add the requirement
	const prereqLib = usePrereqLib().data ?? [];
	const prereqTypes = (usePrereqTypes().data ?? []).map((t) => t.name);
	const [selectedPrereqs, setSelectedPrereqs] = useState<PrereqLine[]>([]);
	const [reqType, setReqType] = useState('');
	const [reqText, setReqText] = useState('');

	const createProcedure = useCreateProcedure();
	const createType = useCreatePrereqType();
	const createPrereq = useCreatePrereq();
	const saving = createProcedure.isPending;

	// Library requirements already known for the chosen type — drives the requirement combobox.
	const itemsForType = useMemo(() => {
		const t = reqType.trim().toLowerCase();
		const seen = new Set<string>();
		return prereqLib
			.filter((p) => (t ? p.type.toLowerCase() === t : true))
			.map((p) => p.text)
			.filter((text) => (seen.has(text) ? false : (seen.add(text), true)));
	}, [prereqLib, reqType]);

	/**
	 * Grow the reusable library so this type+requirement is pre-populated next time.
	 * Best-effort: library writes need TENANT_ADMIN, so authors get a 403 — the procedure
	 * keeps its own snapshot regardless, so we just skip persistence silently. 409 = it
	 * already exists, which is also fine. The mutations invalidate the library queries.
	 */
	async function persistToLibrary(type: string, text: string) {
		try {
			if (type && !prereqTypes.some((t) => t.toLowerCase() === type.toLowerCase())) {
				await createType.mutateAsync(type);
			}
			const exists = prereqLib.some(
				(p) =>
					p.type.toLowerCase() === type.toLowerCase() &&
					p.text.toLowerCase() === text.toLowerCase()
			);
			if (!exists) {
				await createPrereq.mutateAsync({ type, text });
			}
		} catch {
			/* not permitted or already exists — the procedure's snapshot still applies */
		}
	}

	function addRequirement() {
		const text = reqText.trim();
		if (!text) return;
		const type = reqType.trim();
		setSelectedPrereqs((s) => [...s, { type, text }]);
		void persistToLibrary(type, text);
		setReqText(''); // keep the type so several requirements of one type add quickly
	}
	function removeSelected(i: number) {
		setSelectedPrereqs((s) => s.filter((_, j) => j !== i));
	}
	function closeNew() {
		setShowNew(false);
		setTitle('');
		setDocType('SOP');
		setSelectedPrereqs([]);
		setReqType('');
		setReqText('');
	}

	function sortBy(k: SortKey) {
		if (k === sortKey) setSortDir((d) => (d * -1) as 1 | -1);
		else {
			setSortKey(k);
			setSortDir(1);
		}
	}

	const view = useMemo(() => {
		const t = q.trim().toLowerCase();
		const filtered = rows.filter(
			(r) =>
				!t ||
				r.title.toLowerCase().includes(t) ||
				r.documentNumber.toLowerCase().includes(t) ||
				r.owner.toLowerCase().includes(t)
		);
		return [...filtered].sort((a, b) => {
			const x = (a[sortKey] ?? '') as string;
			const y = (b[sortKey] ?? '') as string;
			return String(x).localeCompare(String(y)) * sortDir;
		});
	}, [rows, q, sortKey, sortDir]);

	async function create() {
		try {
			const p = await createProcedure.mutateAsync({
				title,
				type: docType,
				prerequisites: selectedPrereqs
			});
			toast(`Created ${p.documentNumber}`, 'success');
			closeNew();
			navigate(`/procedures/${p.id}`);
		} catch (e) {
			toast((e as Error).message, 'danger');
		}
	}

	const columns: { key: SortKey; label: string }[] = [
		{ key: 'documentNumber', label: 'Document' },
		{ key: 'title', label: 'Title' },
		{ key: 'type', label: 'Type' },
		{ key: 'owner', label: 'Owner' },
		{ key: 'state', label: 'Status' },
		{ key: 'effectiveDate', label: 'Effective' },
		{ key: 'nextReviewDate', label: 'Next review' }
	];

	return (
		<>
			<div className="toolbar">
				<div style={{ maxWidth: 320, flex: '0 1 320px' }}>
					<InputGroup
						leftIcon="search"
						placeholder="Search title, document #, owner…"
						value={q}
						onChange={(e) => setQ(e.currentTarget.value)}
					/>
				</div>
				<HTMLSelect
					options={STATE_ITEMS}
					value={state}
					onChange={(e) => setState(e.currentTarget.value)}
				/>
				<span className="muted" style={{ fontSize: 12 }}>
					{view.length} of {rows.length}
				</span>
				<div className="grow" />
				<Button intent="primary" icon="add" onClick={() => setShowNew(true)} text="New procedure" />
			</div>

			<HTMLTable striped interactive className="full">
				<thead>
					<tr>
						{columns.map((c) => (
							<th key={c.key} className="click" onClick={() => sortBy(c.key)}>
								{c.label}
								{sortKey === c.key ? (sortDir === 1 ? ' ▲' : ' ▼') : ''}
							</th>
						))}
					</tr>
				</thead>
				<tbody>
					{loading ? (
						<tr>
							<td colSpan={columns.length} className="muted">
								Loading…
							</td>
						</tr>
					) : view.length === 0 ? (
						<tr>
							<td colSpan={columns.length} className="muted">
								No procedures match.
							</td>
						</tr>
					) : (
						view.map((p) => (
							<tr key={p.id} className="click" onClick={() => navigate(`/procedures/${p.id}`)}>
								<td className="mono">{p.documentNumber}</td>
								<td style={{ fontWeight: 500 }}>{p.title}</td>
								<td className="mono">{p.type}</td>
								<td>{p.owner}</td>
								<td>
									<Tag intent={statusIntent(p.state)} minimal>
										{p.state}
									</Tag>
								</td>
								<td className="mono">{p.effectiveDate ?? '—'}</td>
								<td className="mono">{p.nextReviewDate ?? '—'}</td>
							</tr>
						))
					)}
				</tbody>
			</HTMLTable>

			<Dialog isOpen={showNew} onClose={closeNew} title="New procedure" icon="document">
				<DialogBody>
					<p className="muted" style={{ marginTop: 0 }}>
						Creates a draft you can author and submit for approval.
					</p>
					<FormGroup label="Type">
						<HTMLSelect
							fill
							options={TYPE_ITEMS}
							value={docType}
							onChange={(e) => setDocType(e.currentTarget.value)}
						/>
					</FormGroup>
					<FormGroup
						label="Title"
						helperText="A document number is assigned automatically (e.g. SOP-0001)."
					>
						<InputGroup
							value={title}
							onChange={(e) => setTitle(e.currentTarget.value)}
							placeholder="Procedure title"
							fill
						/>
					</FormGroup>

					<FormGroup label="Prerequisites" labelInfo="(optional)">
						{selectedPrereqs.length > 0 && (
							<div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 10 }}>
								{selectedPrereqs.map((p, i) => (
									<Tag key={i} minimal onRemove={() => removeSelected(i)}>
										{prereqLabel(p)}
									</Tag>
								))}
							</div>
						)}
						<div style={{ display: 'flex', gap: 6, alignItems: 'flex-start' }}>
							<div style={{ flex: '0 0 38%' }}>
								<Combobox
									fill
									items={prereqTypes}
									value={reqType}
									onChange={setReqType}
									placeholder="Type (e.g. Software)"
								/>
							</div>
							<div style={{ flex: 1 }}>
								<Combobox
									fill
									items={itemsForType}
									value={reqText}
									onChange={setReqText}
									placeholder={
										reqType.trim()
											? `Select or add ${reqType.trim().toLowerCase()}…`
											: 'Requirement — select or add…'
									}
								/>
							</div>
							<Button
								icon="add"
								disabled={!reqText.trim()}
								onClick={addRequirement}
								aria-label="Add requirement"
							/>
						</div>
						<div className="muted" style={{ fontSize: 12, marginTop: 6 }}>
							Pick a type, then choose an existing requirement or type a new one.
						</div>
					</FormGroup>
				</DialogBody>
				<DialogFooter
					actions={
						<>
							<Button onClick={closeNew} text="Cancel" />
							<Button
								intent="primary"
								onClick={create}
								disabled={!title || saving}
								loading={saving}
								text="Create"
							/>
						</>
					}
				/>
			</Dialog>
		</>
	);
}

// web-svelte-legacy/src/routes/(app)/procedures/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { api } from '$lib/api';
	import { toast } from '$lib/stores';
	import { badgeColor } from '$lib/ui';
	import {
		Table,
		TableHead,
		TableHeadCell,
		TableBody,
		TableBodyRow,
		TableBodyCell,
		Badge,
		Button,
		ButtonGroup,
		Modal,
		Input,
		Label,
		Select
	} from 'flowbite-svelte';

	type Proc = {
		id: string;
		documentNumber: string;
		title: string;
		type: string;
		owner: string;
		state: string;
		effectiveDate: string | null;
		nextReviewDate: string | null;
	};

	const TYPE_ITEMS = [
		{ value: 'SOP', name: 'SOP' },
		{ value: 'POLICY', name: 'Policy' },
		{ value: 'WORK_INSTRUCTION', name: 'Work instruction' },
		{ value: 'FORM', name: 'Form' },
		{ value: 'JOB_AID', name: 'Job aid' }
	];

	const STATE_ITEMS = [
		{ value: 'ALL', name: 'All statuses' },
		{ value: 'DRAFT', name: 'Draft' },
		{ value: 'IN_REVIEW', name: 'In review' },
		{ value: 'APPROVED', name: 'Approved' },
		{ value: 'EFFECTIVE', name: 'Effective' },
		{ value: 'UNDER_REVIEW', name: 'Under review' },
		{ value: 'RETIRED', name: 'Retired' }
	];

	const COLUMNS: { key: keyof Proc; label: string }[] = [
		{ key: 'documentNumber', label: 'Document' },
		{ key: 'title', label: 'Title' },
		{ key: 'type', label: 'Type' },
		{ key: 'owner', label: 'Owner' },
		{ key: 'state', label: 'Status' },
		{ key: 'effectiveDate', label: 'Effective' },
		{ key: 'nextReviewDate', label: 'Next review' }
	];

	let rows = $state<Proc[]>([]);
	let loading = $state(true);
	let state = $state('ALL');
	let q = $state('');
	let sortKey = $state<keyof Proc>('documentNumber');
	let sortDir = $state<1 | -1>(1);

	function sortBy(k: keyof Proc) {
		if (sortKey === k) sortDir = (sortDir * -1) as 1 | -1;
		else {
			sortKey = k;
			sortDir = 1;
		}
	}
	let showNew = $state(false);
	let docType = $state('SOP');
	let title = $state('');
	let saving = $state(false);

	let filtered = $derived(
		rows.filter((r) => {
			const t = q.trim().toLowerCase();
			return (
				!t ||
				r.title.toLowerCase().includes(t) ||
				r.documentNumber.toLowerCase().includes(t) ||
				r.owner.toLowerCase().includes(t)
			);
		})
	);

	let sorted = $derived(
		[...filtered].sort((a, b) => {
			const x = (a[sortKey] ?? '') as string;
			const y = (b[sortKey] ?? '') as string;
			return x.localeCompare(y) * sortDir;
		})
	);

	async function load() {
		loading = true;
		try {
			rows = await api.get<Proc[]>(`/api/v1/procedures?state=${state}`);
		} catch (e) {
			toast((e as Error).message, 'err');
		} finally {
			loading = false;
		}
	}

	async function create() {
		saving = true;
		try {
			const p = await api.post<{ id: string; documentNumber: string }>('/api/v1/procedures', {
				title,
				type: docType
			});
			toast(`Created ${p.documentNumber}`, 'ok');
			showNew = false;
			docType = 'SOP';
			title = '';
			await goto(`/procedures/${p.id}`);
		} catch (err) {
			toast((err as Error).message, 'err');
		} finally {
			saving = false;
		}
	}

	onMount(load);
</script>

<div class="toolbar">
	<div class="grow" style="max-width: 360px">
		<Input placeholder="Search title, document #, owner…" bind:value={q} />
	</div>
	<div style="width: 180px">
		<Select items={STATE_ITEMS} bind:value={state} onchange={load} />
	</div>
	<span class="text-xs text-gray-400">{filtered.length} of {rows.length}</span>
	<div class="grow"></div>
	<ButtonGroup class="actions">
		<Button color="green" onclick={() => (showNew = true)}>
			<svg class="me-1.5 size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14" /></svg>
			New procedure
		</Button>
	</ButtonGroup>
</div>

<Table hoverable shadow>
	<TableHead>
		{#each COLUMNS as c (c.key)}
			<TableHeadCell class="sortable" onclick={() => sortBy(c.key)}>
				{c.label}<span class="sort-ind">{sortKey === c.key ? (sortDir === 1 ? '▲' : '▼') : '↕'}</span>
			</TableHeadCell>
		{/each}
	</TableHead>
	<TableBody>
		{#if loading}
			<TableBodyRow><TableBodyCell colspan={7} class="text-center text-gray-400">Loading…</TableBodyCell></TableBodyRow>
		{:else}
			{#each sorted as p (p.id)}
				<TableBodyRow class="cursor-pointer" onclick={() => goto(`/procedures/${p.id}`)}>
					<TableBodyCell class="font-mono text-gray-600">{p.documentNumber}</TableBodyCell>
					<TableBodyCell class="font-medium text-gray-900">{p.title}</TableBodyCell>
					<TableBodyCell class="font-mono text-gray-500">{p.type}</TableBodyCell>
					<TableBodyCell class="font-normal text-gray-600">{p.owner}</TableBodyCell>
					<TableBodyCell><Badge color={badgeColor(p.state)}>{p.state}</Badge></TableBodyCell>
					<TableBodyCell class="font-mono text-gray-500">{p.effectiveDate ?? '—'}</TableBodyCell>
					<TableBodyCell class="font-mono text-gray-500">{p.nextReviewDate ?? '—'}</TableBodyCell>
				</TableBodyRow>
			{:else}
				<TableBodyRow><TableBodyCell colspan={7} class="text-center text-gray-400">No procedures match.</TableBodyCell></TableBodyRow>
			{/each}
		{/if}
	</TableBody>
</Table>

<Modal title="New procedure" bind:open={showNew} size="sm">
	<p class="-mt-2 text-sm text-gray-500">Creates a draft you can author and submit for approval.</p>
	<div>
		<Label class="mb-2">Type</Label>
		<Select items={TYPE_ITEMS} bind:value={docType} />
		<p class="mt-1 text-xs text-gray-400">
			A document number is assigned automatically (e.g. SOP-0001).
		</p>
	</div>
	<div>
		<Label class="mb-2">Title</Label>
		<Input bind:value={title} placeholder="Procedure title" required />
	</div>
	{#snippet footer()}
		<div class="flex w-full justify-end gap-2">
			<Button color="alternative" onclick={() => (showNew = false)}>Cancel</Button>
			<Button color="green" disabled={saving || !title} onclick={create}>
				{saving ? 'Creating…' : 'Create'}
			</Button>
		</div>
	{/snippet}
</Modal>
