// web/src/pages/SignIn.tsx
import { useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, FormGroup, InputGroup, Button, Callout } from '@blueprintjs/core';
import { useLogin } from '../lib/queries';

export default function SignIn() {
	const navigate = useNavigate();
	const login = useLogin();
	const [email, setEmail] = useState('admin@example.com');
	const [password, setPassword] = useState('admin');
	const [error, setError] = useState('');
	const busy = login.isPending;

	async function submit(e: FormEvent) {
		e.preventDefault();
		setError('');
		try {
			await login.mutateAsync({ username: email, password });
			navigate('/');
		} catch {
			setError('Invalid email or password.');
		}
	}

	return (
		<div className="auth">
			<Card className="auth-card" elevation={2}>
				<div className="auth-brand">
					<span className="mark">
						<span />
					</span>
					sopstore
				</div>
				<p className="page-sub" style={{ marginTop: 6 }}>
					Quality &amp; SOP control platform
				</p>

				{error && (
					<Callout intent="danger" style={{ marginBottom: 14 }}>
						{error}
					</Callout>
				)}

				<form onSubmit={submit}>
					<FormGroup label="Email" labelFor="email">
						<InputGroup
							id="email"
							type="email"
							value={email}
							onChange={(e) => setEmail(e.currentTarget.value)}
							autoComplete="username"
							large
							fill
						/>
					</FormGroup>
					<FormGroup label="Password" labelFor="password">
						<InputGroup
							id="password"
							type="password"
							value={password}
							onChange={(e) => setPassword(e.currentTarget.value)}
							autoComplete="current-password"
							large
							fill
						/>
					</FormGroup>
					<Button type="submit" intent="primary" large fill loading={busy} text="Sign in" />
				</form>

				<p className="page-sub" style={{ textAlign: 'center', marginTop: 16, marginBottom: 0 }}>
					Dev login is pre-filled. SSO available on the server login page.
				</p>
			</Card>
		</div>
	);
}

// web-svelte-legacy/src/routes/signin/+page.svelte
<script lang="ts">
	import { login } from '$lib/api';
	import { goto } from '$app/navigation';
	import { Button, Input, Label, Alert } from 'flowbite-svelte';

	let email = $state('admin@example.com');
	let password = $state('admin');
	let error = $state('');
	let busy = $state(false);

	async function submit(e: Event) {
		e.preventDefault();
		busy = true;
		error = '';
		try {
			await login(email, password);
			await goto('/');
		} catch {
			error = 'Invalid email or password.';
		} finally {
			busy = false;
		}
	}
</script>

<svelte:head><title>Sign in · sopstore</title></svelte:head>

<div class="auth">
	<form class="auth-card" onsubmit={submit}>
		<div class="brand"><span class="dot"></span> sopstore</div>
		<p class="page-sub" style="margin: 6px 0 22px">Quality &amp; SOP control platform</p>

		{#if error}
			<Alert color="red" class="mb-4">{error}</Alert>
		{/if}

		<div class="mb-4">
			<Label class="mb-2">Email</Label>
			<Input type="email" bind:value={email} autocomplete="username" required />
		</div>
		<div class="mb-5">
			<Label class="mb-2">Password</Label>
			<Input type="password" bind:value={password} autocomplete="current-password" required />
		</div>
		<Button type="submit" color="green" class="w-full" disabled={busy}>
			{busy ? 'Signing in…' : 'Sign in'}
		</Button>
		<p class="page-sub" style="text-align: center; margin-top: 16px">
			Dev login is pre-filled. SSO available on the server login page.
		</p>
	</form>
</div>
