// web-svelte-legacy/src/routes/(app)/runs/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { api } from '$lib/api';
	import { toast } from '$lib/stores';
	import { badgeColor, dt } from '$lib/ui';
	import {
		Table,
		TableHead,
		TableHeadCell,
		TableBody,
		TableBodyRow,
		TableBodyCell,
		Badge,
		Spinner,
		Input
	} from 'flowbite-svelte';

	type RunRow = {
		runId: string;
		procedureId: string;
		procedureTitle: string;
		state: string;
		startedAt: string;
		durationSeconds: number | null;
		deviationCount: number;
	};
	type Stats = {
		procedureId: string;
		procedureTitle: string;
		runCount: number;
		completionPct: number;
		avgDurationSeconds: number | null;
		deviationCount: number;
	};

	let history = $state<RunRow[]>([]);
	let analytics = $state<Stats[]>([]);
	let loading = $state(true);
	let q = $state('');

	let fAnalytics = $derived(
		analytics.filter((a) => a.procedureTitle.toLowerCase().includes(q.trim().toLowerCase()))
	);
	let fHistory = $derived(
		history.filter((r) => r.procedureTitle.toLowerCase().includes(q.trim().toLowerCase()))
	);

	const dur = (s: number | null) => (s == null ? '—' : s < 60 ? `${s}s` : `${Math.round(s / 60)}m`);

	onMount(async () => {
		try {
			const d = await api.get<{ history: RunRow[]; analytics: Stats[] }>('/api/v1/runs');
			history = d.history;
			analytics = d.analytics;
		} catch (e) {
			toast((e as Error).message, 'err');
		} finally {
			loading = false;
		}
	});
</script>

<p class="text-sm text-gray-500 mb-3">Execution analytics and recent runs across all procedures.</p>

{#if loading}
	<div class="center-screen"><Spinner color="green" /></div>
{:else}
	<div class="toolbar">
		<div class="grow" style="max-width: 360px"><Input placeholder="Filter by procedure…" bind:value={q} /></div>
		<span class="text-xs text-gray-400">{fHistory.length} run(s)</span>
	</div>
	<h2 class="mb-3 text-sm font-semibold text-gray-900">Per-procedure analytics</h2>
	<Table hoverable shadow>
		<TableHead>
			<TableHeadCell>Procedure</TableHeadCell>
			<TableHeadCell>Runs</TableHeadCell>
			<TableHeadCell>Completion</TableHeadCell>
			<TableHeadCell>Avg duration</TableHeadCell>
			<TableHeadCell>Deviations</TableHeadCell>
		</TableHead>
		<TableBody>
			{#each fAnalytics as a (a.procedureId)}
				<TableBodyRow class="cursor-pointer" onclick={() => goto(`/procedures/${a.procedureId}`)}>
					<TableBodyCell class="font-normal">{a.procedureTitle}</TableBodyCell>
					<TableBodyCell class="font-mono">{a.runCount}</TableBodyCell>
					<TableBodyCell><Badge color={a.completionPct === 100 ? 'green' : 'yellow'}>{a.completionPct}%</Badge></TableBodyCell>
					<TableBodyCell class="font-mono">{dur(a.avgDurationSeconds)}</TableBodyCell>
					<TableBodyCell class="font-mono">{a.deviationCount}</TableBodyCell>
				</TableBodyRow>
			{:else}
				<TableBodyRow><TableBodyCell colspan={5} class="text-center text-gray-400">No runs yet.</TableBodyCell></TableBodyRow>
			{/each}
		</TableBody>
	</Table>

	<h2 class="mt-8 mb-3 text-sm font-semibold text-gray-900">Recent runs</h2>
	<Table hoverable shadow>
		<TableHead>
			<TableHeadCell>Procedure</TableHeadCell>
			<TableHeadCell>State</TableHeadCell>
			<TableHeadCell>Started</TableHeadCell>
			<TableHeadCell>Duration</TableHeadCell>
			<TableHeadCell>Deviations</TableHeadCell>
		</TableHead>
		<TableBody>
			{#each fHistory as r (r.runId)}
				<TableBodyRow>
					<TableBodyCell class="font-normal">{r.procedureTitle}</TableBodyCell>
					<TableBodyCell><Badge color={badgeColor(r.state)}>{r.state}</Badge></TableBodyCell>
					<TableBodyCell class="font-mono text-gray-500">{dt(r.startedAt)}</TableBodyCell>
					<TableBodyCell class="font-mono">{dur(r.durationSeconds)}</TableBodyCell>
					<TableBodyCell class="font-mono">{r.deviationCount}</TableBodyCell>
				</TableBodyRow>
			{:else}
				<TableBodyRow><TableBodyCell colspan={5} class="text-center text-gray-400">No runs yet.</TableBodyCell></TableBodyRow>
			{/each}
		</TableBody>
	</Table>
{/if}

// web/src/pages/Runs.tsx
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { HTMLTable, InputGroup, Tag, Spinner } from '@blueprintjs/core';
import { statusIntent, dt, dur } from '../lib/ui';
import { useRuns } from '../lib/queries';

export default function Runs() {
	const navigate = useNavigate();
	const { data, isLoading: loading } = useRuns();
	const history = useMemo(() => data?.history ?? [], [data]);
	const analytics = useMemo(() => data?.analytics ?? [], [data]);
	const [q, setQ] = useState('');

	const t = q.trim().toLowerCase();
	const fAnalytics = useMemo(
		() => analytics.filter((a) => a.procedureTitle.toLowerCase().includes(t)),
		[analytics, t]
	);
	const fHistory = useMemo(
		() => history.filter((r) => r.procedureTitle.toLowerCase().includes(t)),
		[history, t]
	);

	if (loading)
		return (
			<div className="center-screen">
				<Spinner />
			</div>
		);

	return (
		<>
			<p className="page-sub">Execution analytics and recent runs across all procedures.</p>

			<div className="toolbar">
				<div style={{ maxWidth: 320, flex: '0 1 320px' }}>
					<InputGroup
						leftIcon="search"
						placeholder="Filter by procedure…"
						value={q}
						onChange={(e) => setQ(e.currentTarget.value)}
					/>
				</div>
				<span className="muted" style={{ fontSize: 12 }}>
					{fHistory.length} run(s)
				</span>
			</div>

			<div className="section-h">Per-procedure analytics</div>
			<HTMLTable striped interactive className="full">
				<thead>
					<tr>
						<th>Procedure</th>
						<th>Runs</th>
						<th>Completion</th>
						<th>Avg duration</th>
						<th>Deviations</th>
					</tr>
				</thead>
				<tbody>
					{fAnalytics.length === 0 ? (
						<tr>
							<td colSpan={5} className="muted">
								No runs yet.
							</td>
						</tr>
					) : (
						fAnalytics.map((a) => (
							<tr
								key={a.procedureId}
								className="click"
								onClick={() => navigate(`/procedures/${a.procedureId}`)}
							>
								<td>{a.procedureTitle}</td>
								<td className="mono">{a.runCount}</td>
								<td>
									<Tag intent={a.completionPct === 100 ? 'success' : 'warning'} minimal>
										{a.completionPct}%
									</Tag>
								</td>
								<td className="mono">{dur(a.avgDurationSeconds)}</td>
								<td className="mono">{a.deviationCount}</td>
							</tr>
						))
					)}
				</tbody>
			</HTMLTable>

			<div className="section-h">Recent runs</div>
			<HTMLTable striped className="full">
				<thead>
					<tr>
						<th>Procedure</th>
						<th>State</th>
						<th>Started</th>
						<th>Duration</th>
						<th>Deviations</th>
					</tr>
				</thead>
				<tbody>
					{fHistory.length === 0 ? (
						<tr>
							<td colSpan={5} className="muted">
								No runs yet.
							</td>
						</tr>
					) : (
						fHistory.map((r) => (
							<tr key={r.runId}>
								<td>{r.procedureTitle}</td>
								<td>
									<Tag intent={statusIntent(r.state)} minimal>
										{r.state}
									</Tag>
								</td>
								<td className="mono muted">{dt(r.startedAt)}</td>
								<td className="mono">{dur(r.durationSeconds)}</td>
								<td className="mono">{r.deviationCount}</td>
							</tr>
						))
					)}
				</tbody>
			</HTMLTable>
		</>
	);
}
